### ISSUE TITLE
 Null check operator used on a null value (rootNavigatorKey.currentState!.overlay!.context)

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1037]
### Describe the problem you discovered

```
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00008103-0005718E3460801E, name:My Mac }
{ platform:macOS, arch:x86_64, id:00008103-0005718E3460801E, name:My Mac }
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'CocoaAsyncSocket' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'PromisesObjC-FBLPromises_Privacy' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'PromisesObjC' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'GoogleUtilities-GoogleUtilities_Privacy' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'GoogleUtilities' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'nanopb-nanopb_Privacy' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'nanopb' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'GoogleDataTransport-GoogleDataTransport_Privacy' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.12, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'GoogleDataTransport' from project 'Pods')
/archethic_wallet/macos/Pods/Pods.xcodeproj: warning: The macOS deployment target 'MACOSX_DEPLOYMENT_TARGET' is set to 10.11, but the range of supported deployment target versions is 10.13 to 14.5.99. (in target 'OrderedSet' from project 'Pods')

✓ Built build/macos/Build/Products/Debug/archethic_wallet.app
[IMPORTANT:flutter/shell/platform/darwin/graphics/FlutterDarwinContextMetalSkia.mm(66)] Using the Skia rendering backend (Metal).
2024-07-19 15:24:17.603 archethic_wallet[10302:812838] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.
Connecting to VM Service at ws://127.0.0.1:53828/7ObR4Mzenc0=/ws
[GoRouter] setting initial location /
[GoRouter] Full paths for routes:
             => /
             => /logging_out
             => /biometrics
             => /password
             => /pin
             => /yubikey
             => /intro_configure_security
             => /intro_welcome
             => /intro_welcome_get_first_infos
             => /intro_backup
             => /intro_backup_safety
             => /intro_import
             => /intro_backup_confirm
             => /network_dialog
             => /sendingAnimation
             => /set_password
             => /set_yubikey
             => /home
             => /security_menu_view
             => /customization_menu_view
             => /about_menu_view
             => /nft_list_per_category
             => /nft_creation
             =>   /nft_creation/add_address
             => /messenger_discussion
             => /discussion_details
             => /update_discussion
             => /add_account
             => /add_contact
             => /buy
             => /dex
             => /contact_detail
             => /connectivity_warning
             => /add_token
             => /chart
             => /app_seed_backup
             => /transaction_info
             => /transfer
             => /nft_creation_process_import_tab_aeweb
             => /nft_creation_process_import_tab_http
             => /nft_creation_process_import_tab_ipfs
             => /nft_detail
             => /configure_category_list
             => /create_discussion
             => /settings
             => /create_discussion_validation
             => /add_discussion
             => /update_discussion_add_members
           known full paths for route names:
             add_address => /nft_creation/add_address
[_selectedLanguageProvider] didAddProvider(AvailableLanguage.english)
[_availableLocalesProvider] didAddProvider([en, fr])
[AppWidget] Lifecycle State : AppLifecycleState.inactive
[AppWidget] Lifecycle State : AppLifecycleState.resumed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      AppState.updateDefaultLocale.<anonymous closure> (package:aewallet/main.dart:179:42)
#1      StateController.update (package:riverpod/src/state_controller.dart:32:49)
#2      AppState.updateDefaultLocale (package:aewallet/main.dart:177:56)
#3      AppState.didChangeAppLifecycleStateAsync (package:aewallet/main.dart:154:9)
#4      AppState.didChangeAppLifecycleState (package:aewallet/main.dart:138:5)
#5      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:945:16)
#6      List.forEach (dart:core-patch/growable_array.dart:416:8)
#7      ServicesBinding._handleLifecycleMessage (package:flutter/src/services/binding.dart:284:15)
#8      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
#10     _invoke2 (dart:ui/hooks.dart:344:13)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)

[AuthenticationGuard-Widget] Init state
[AuthenticationGuard-LastInteractionDateProvider] didAddProvider(AsyncLoading<({DateTime? date, bool isStartupValue})>())
[AuthenticationGuard-Provider] didAddProvider(AsyncLoading<AuthenticationGuardState>())
[AuthenticationGuard-Widget] Unschedule lock
```

**Comment by Chralu** [comment]
Not relevant anymore.
