### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1137]
### Describe the problem you discovered

Import a wallet, go to earn Tab, click on farm info, open the explorer for the farm address and click on "archethic wallet" button
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 201 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
errors_patch.dart:50
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
errors_patch.dart:40
#2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:201:12)
scroll_controller.dart:201
#3      ModalBottomSheetState.build.<anonymous closure> (package:modal_bottom_sheet/src/bottom_sheet.dart:417:27)
bottom_sheet.dart:417
#4      _StatusBarGestureDetectorState.build.<anonymous closure>.<anonymous closure> (package:modal_bottom_sheet/src/utils/scroll_to_top_status_bar.dart:47:40)
scroll_to_top_status_bar.dart:47
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:351:24)
recognizer.dart:351
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:656:11)
tap.dart:656
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/t<…>
```

**Comment by redDwarf03** [comment]
https://github.com/jamesblasco/modal_bottom_sheet/issues?q=is%3Aissue+is%3Aopen+not+attached+to+any+scroll+views
