### ISSUE TITLE
Application not found in Play Store

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#1198]
### Describe the problem you discovered

Fix error:

``` 
[_getAppVersionInfoProvider] 2024-12-20 14:13:11.244 providerDidFail(Application not found in Play Store, verify your app id.)
[_getAppVersionInfoProvider] 2024-12-20 14:13:11.244 didUpdateProvider(AsyncError<AppVersionInfo>(error: Application not found in Play Store, verify your app id., stackTrace: #0      fetchAndroid (package:app_version_update/core/functions/fetch_version.dart:79:7)
                             <asynchronous suspension>
                             #1      fetchVersion (package:app_version_update/core/functions/fetch_version.dart:22:9)
fetch_version.dart:22
                             <asynchronous suspension>
                             #2      AppVersionUpdate.checkForUpdates (package:app_version_update/app_version_update.dart:31:18)
app_version_update.dart:31
                             <asynchronous suspension>
                             #3      AppVersionUpdateInfo.getAppVersionInfo (package:aewallet/infrastructure/repositories/app_version_update_info.dart:8:30)
app_version_update_info.dart:8
                             <asynchronous suspension>
                             #4      _getAppVersionInfo (package:aewallet/application/app_version_update_info.dart:21:7)
app_version_update_info.dart:21
                             <asynchronous suspension>
                             #5      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:355:9)
base.dart:355
                             <asynchronous suspension>
                             ))
```

**Comment by redDwarf03** [comment]
https://github.com/kauemurakami/app_version_update/issues/35#issuecomment-2557168846

**Comment by redDwarf03** [comment]
Works with new_version_plus package
