### ISSUE TITLE
Failed assertion: line 4906 pos 12: 'state._element == null': is not true.

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#154]
### Describe the problem you discovered

When we change auth method with PIN, we have an error from appbar widget
```


════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xffffffff)):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4906 pos 12: 'state._element == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was
AppBar
When the exception was thrown, this was the stack
#2      new StatefulElement
#3      StatefulWidget.createElement
#4      Element.inflateWidget
#5      MultiChildRenderObjectElement.inflateWidget
#6      MultiChildRenderObjectElement.mount
...     Normal element mounting (19 frames)
#25     Element.inflateWidget
#26     MultiChildRenderObjectElement.inflateWidget
#27     MultiChildRenderObjectElement.mount
...     Normal element mounting (129 frames)
#156    Element.inflateWidget
#157    MultiChildRenderObjectElement.inflateWidget
#158    MultiChildRenderObjectElement.mount
...     Normal element mounting (243 frames)
#401    Element.inflateWidget
#402    MultiChildRenderObjectElement.inflateWidget
#403    Element.updateChild
#404    RenderObjectElement.updateChildren
#405    MultiChildRenderObjectElement.update
#406    Element.updateChild
#407    ComponentElement.performRebuild
#408    StatefulElement.performRebuild
#409    Element.rebuild
#410    StatefulElement.update
#411    Element.updateChild
#412    ComponentElement.performRebuild
#413    Element.rebuild
#414    ProxyElement.update
#415    Element.updateChild
#416    ComponentElement.performRebuild
#417    Element.rebuild
#418    ProxyElement.update
#419    _InheritedNotifierElement.update
#420    Element.updateChild
#421    SingleChildRenderObjectElement.update
#422    Element.updateChild
#423    ComponentElement.performRebuild
#424    StatefulElement.performRebuild
#425    Element.rebuild
#426    StatefulElement.update
#427    Element.updateChild
#428    SingleChildRenderObjectElement.update
#429    Element.updateChild
#430    SingleChildRenderObjectElement.update
#431    Element.updateChild
#432    ComponentElement.performRebuild
#433    Element.rebuild
#434    ProxyElement.update
#435    Element.updateChild
#436    ComponentElement.performRebuild
#437    StatefulElement.performRebuild
#438    Element.rebuild
#439    BuildOwner.buildScope
#440    WidgetsBinding.drawFrame
#441    RendererBinding._handlePersistentFrameCallback
#442    SchedulerBinding._invokeFrameCallback
#443    SchedulerBinding.handleDrawFrame
#444    SchedulerBinding._handleDrawFrame
#448    _invoke (dart:ui/hooks.dart:151:10)
#449    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#450    _drawFrame (dart:ui/hooks.dart:115:31)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Each child must be laid out exactly once.
The relevant error-causing widget was
AppBar
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Updated layout information required for RenderErrorBox#eba66 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
'package:flutter/src/rendering/object.dart':
Failed assertion: line 2817 pos 12: '!_needsLayout'

════════════════════════════════════════════════════════════════════════════════

```

**Comment by redDwarf03** [comment]
The widget that display notification icon meet a pb... don't know why for the moment..
