### ISSUE TITLE
Scroll bar doesn't work with desktop platform

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#386]
### Describe the problem you discovered

```
The Scrollbar attempted to use the PrimaryScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to.A ScrollView with an Axis.vertical ScrollDirection on mobile platforms will automatically use the PrimaryScrollController if the user has not provided a ScrollController. To use the PrimaryScrollController explicitly, set ScrollView.primary to true for the Scrollable widget.

When the exception was thrown, this was the stack
#0      RawScrollbarState._debugCheckHasValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1503
#1      RawScrollbarState._debugCheckHasValidScrollPosition
package:flutter/…/widgets/scrollbar.dart:1528
#2      RawScrollbarState._debugScheduleCheckHasValidScrollPosition.<anonymous closure>
package:flutter/…/widgets/scrollbar.dart:1456
#3      SchedulerBinding._invokeFrameCallback
package:flutter/…/scheduler/binding.dart:1175
#4      SchedulerBinding.handleDrawFrame
package:flutter/…/scheduler/binding.dart:1113
#5      SchedulerBinding._handleDrawFrame
package:flutter/…/scheduler/binding.dart:1015
#6      _invoke (dart:ui/hooks.dart:148:13)
#7      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#8      _drawFrame (dart:ui/hooks.dart:115:31)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The Scrollbar's ScrollController has no ScrollPosition attached.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by animation library ═════════════════════════════════
The Scrollbar's ScrollController has no ScrollPosition attached.
```

**Comment by redDwarf03** [comment]
add scrollController in Scrollbar and SingleChildScrollView widgets
```
child: Scrollbar(
              controller: scrollController,
              thumbVisibility: true,
              child: SingleChildScrollView(
                controller: scrollController,
```
