### ISSUE TITLE
Add biometrics feature

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#462]
### Is your feature request related to a problem?

with Windows, we have
``` 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(biometricOnlyNotSupported, Windows doesn't support the biometricOnly parameter., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      LocalAuthWindows.authenticate (package:local_auth_windows/local_auth_windows.dart:44:13)
<asynchronous suspension>
#3      AuthentificationMethodDialog.getDialog.<anonymous closure>.<anonymous closure> (package:aewallet/ui/widgets/dialogs/authentification_method_dialog.dart:71:34)
<asynchronous suspension>
```

**Comment by redDwarf03** [comment]
The Windows version will be decommissioned when the mobile version and chrome extension are up to the expected standard. This issue will not be addressed
