### ISSUE TITLE
Error with riverpod when remove wallet

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#467]
### Describe the problem you discovered

when we create a wallet and remove directly, an error occurs

```
[log] [CheckTransactionScheduler] cancelling scheduler

════════ Exception caught by widgets library ═══════════════════════════════════
Got a stack frame from package:stack_trace, where a vm or web frame was expected. This can happen if FlutterError.demangleStackTrace was not set in an environment that propagates non-standard stack traces to the framework, such as during tests.
'package:flutter/src/foundation/stack_frame.dart':
Failed assertion: line 192 pos 7: 'line != '===== asynchronous gap ===========================''

The relevant error-causing widget was
MenuWidgetWallet
════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:riverpod/src/async_notifier/base.dart': Failed assertion: line 219 pos 12: '_builtFuture == null': Bad state
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      FutureHandlerProviderElementMixin.handleFuture
#3      FutureProviderElement.create
#4      ProviderElementBase.buildState
#5      ProviderElementBase._performBuild
#6      ProviderElementBase.flush
#7      _ProviderScheduler._performRefresh
#8      _ProviderScheduler._task
#9      _UncontrolledProvide<…>
```

**Comment by Chralu** [comment]
https://github.com/archethic-foundation/archethic-wallet/pull/650 fixes this issue.

When deleting wallet, you still get logs like :
```
[account_name] didUpdateProvider(AsyncError<Contact>(error: Exception, stackTrace: #0      DBHelper.getContactWithName
package:aewallet/…/data/appdb.dart:139
       <asynchronous suspension>
#1      _getContactWithName
package:aewallet/application/contact.dart:43
       <asynchronous suspension>
#2      FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure>
package:riverpod/…/async_notifier/base.dart:291
       <asynchronous suspension>
       ))
```

Which is an expected bahavior : currently, `ContactProviders.getContactWithName` throws `Exception` when the searched `Contact` does not exist.
Yet, the exception is handled by the provider, and `Widgets` adapt their behavior to those failures.


We could choose to change the `ContactProviders.getContactWithName` to return `null` when searched `Contact` does not exist.
This is a choice to discuss, feel free to share your mind 😀

**Comment by redDwarf03** [comment]
@charlu. i prefer to return null because it's not a functional error for me... we will fix if you are agree this exception question in other issue
