### ISSUE TITLE
Error in log when subscription is not opened

### ISSUE THREAD

**Issue by redDwarf03** [redDwarf03/archethic_mobile_wallet#603]
### Describe the problem you discovered

When a transaction is validated with < 100% of nodes, an error occurs in the console:

```
2
[getLastTransaction] requestHttp.body=query {
                       __typename
                       _xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: lastTransaction(address: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx") {
                         __typename
                         ...fields
                       }
                     }
                     
                     fragment fields on Transaction {
                       __typename
                       address
                     }
[log] >>> Transaction confirmed xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx <<< 14 / 14
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Tried to read a provider from a ProviderContainer that was already disposed
#0      ProviderContainer.readProviderElement
package:riverpod/…/framework/container.dart:447
#1      ProviderElementProxy.read
package:riverpod/…/framework/proxy_provider_listenable.dart:114
#2      ProviderContainer.read
package:riverpod/…/framework/container.dart:251
#3      ProviderElementBase.read
package:riverpod/…/framework/element.dart:682
#4      AddTokenFormNotifier.send.<anonymous closure>
package:aewallet/…/bloc/provider.dart:317
#5      ArchethicTransactionSender._listenTransactionConfirmed.<anonymous closure>
package:aewallet/…/confirmations/archethic_transaction_sender.dart:186
#6      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _BufferingStreamSubscription._add (dart:async/s<…>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Can't push event on a closed channel
#0      PhoenixChannel.pushEvent
package:phoenix_socket/src/channel.dart:277
#1      PhoenixChannel.push
package:phoenix_socket/src/channel.dart:249
#2      PhoenixLink.request
package:aewallet/…/confirmations/phoenix_link.dart:83
<asynchronous suspension>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Can't push event on a closed channel
#0      PhoenixChannel.pushEvent
package:phoenix_socket/src/channel.dart:277
#1      PhoenixChannel.push
package:phoenix_socket/src/channel.dart:249
#2      PhoenixLink.request
package:aewallet/…/confirmations/phoenix_link.dart:83
<asynchronous suspension>
```

**Comment by redDwarf03** [comment]
Example too when account is created

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
Consider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.
#0      State.context.<anonymous closure>
package:flutter/…/widgets/framework.dart:935
#1      State.context
package:flutter/…/widgets/framework.dart:941
#2      _AddAccountConfirmState._showSendSucceed
package:aewallet/…/components/add_account_confirm_sheet.dart:114
<asynchronous suspension>
#3      _AddAccountConfirmState._registerBus.<anonymous closure>
package:aewallet/…/components/add_account_confirm_sheet.dart:73
<asynchronous suspension>
```
