### ISSUE TITLE
Uncaught exception on wallet creation

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#915]
### Describe the problem you discovered

# Error : 

```log
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:4738:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:4752:6)
#2      Element.dependOnInheritedWidgetOfExactType (package:flutter/src/widgets/framework.dart:4771:12)
#3      Localizations.of (package:flutter/src/widgets/localizations.dart:529:48)
#4      AppLocalizations.of (package:flutter_gen/gen_l10n/localizations.dart:68:26)
#5      SecurityManager.checkDeviceSecurity (package:aewallet/util/security_manager.dart:63:44)
<asynchronous sus<…>
```

# Analysis

in `main.dart`, we use `BuildContext` after a navigation operation : 

```dart
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      await initializeProviders();
      await checkLoggedIn();    // ==> triggers navigation

      // ==> From here, context is invalid
      await SecurityManager().checkDeviceSecurity(ref, context);
      await ref
          .read(LocalDataMigrationProviders.localDataMigration.notifier)
          .migrateLocalData();
    });
  }
```

**Comment by redDwarf03** [comment]
fixed

**Comment by redDwarf03** [comment]
https://github.com/archethic-foundation/archethic-wallet/commit/0cd30114e4195b2fe6356ede2a37d737b44091ba
