### ISSUE TITLE
Exception when removing wallet

### ISSUE THREAD

**Issue by Chralu** [redDwarf03/archethic_mobile_wallet#978]
### Describe the problem you discovered

# howto reproduce issue

1. launch aewallet with a wallet imported
2. remove wallet

an Exception is raised : 
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5013 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5013:12)
#3      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:566:20)
#4      ProviderBase.addListener.<anonymous closure> (package:riverpod/src/framework/provider_base.dart:98:41)
#5      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#6      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/element.dart:525:28)
#7      ResultData.map (package:riverpod/src/result.dart:74:16)
#8      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:519:14)
#9      ProviderElementBase._performBuild (package:riverpod/src/framework/element.dart:358:7)
#10     ProviderElementBase.flush (package:riverpod/src/framework/element.dart:307:7)
#11     ProviderScheduler._performRefresh (package:riverpod/src/framework/scheduler.dart:94:41)
#12     ProviderScheduler._task (package:riverpod/src/framework/scheduler.dart:82:5)
#13     ProviderScheduler.vsync.<anonymous closure>.invoke (package:riverpod/src/framework/scheduler.dart:41:15)
#14     _UncontrolledProviderScopeElement.build (package:flutter_riverpod/src/framework.dart:396:12)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#18     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#22     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1169:5)
#23     _invoke (dart:ui/hooks.dart:312:13)
#24     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:399:5)
#25     _drawFrame (dart:ui/hooks.dart:283:31)

[AuthenticationGuard-Provider] didUpdateProvider(AsyncData<AuthenticationGuardState>(value: AuthenticationGuardState(lockDate: null, timerEnabled: true)))
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5013 pos 12: '_lifecycleState != _ElementLifecycle.defunct': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:5013:12)
#3      ConsumerStatefulElement.watch.<anonymous closure>.<anonymous closure> (package:flutter_riverpod/src/consumer.dart:566:20)
#4      ProviderBase.addListener.<anonymous closure> (package:riverpod/src/framework/provider_base.dart:98:41)
#5      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#6      ProviderElementBase._notifyListeners.<anonymous closure> (package:riverpod/src/framework/element.dart:525:28)
#7      ResultData.map (package:riverpod/src/result.dart:74:16)
#8      ProviderElementBase._notifyListeners (package:riverpod/src/framework/element.dart:519:14)
#9      ProviderElementBase.setState (package:riverpod/src/framework/element.dart:138:7)
#10     AsyncTransition.asyncTransition (package:riverpod/src/common.dart:28:7)
#11     FutureHandlerProviderElementMixin.onData (package:riverpod/src/async_notifier/base.dart:277:7)
#12     FutureHandlerProviderElementMixin._handleAsync.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:383:11)
#13     FutureHandlerProviderElementMixin.handleFuture.<anonymous closure>.<anonymous closure> (package:riverpod/src/async_notifier/base.dart:350:15)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:867:13)
#16     Future._completeWithValue (dart:async/future_impl.dart:643:5)
<asynchronous suspension>
```

**Comment by Chralu** [comment]
# Analysis

Issue comes from usage of a provider while `AutoLockGuard` is disposed.
